-- CircuitTrack PostgreSQL schema.
-- The deployed application creates these tables automatically through SQLAlchemy.
-- This file is also kept as a portable SQL deliverable for the database project.

CREATE TABLE customer (
    customer_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100),
    street VARCHAR(100),
    city VARCHAR(50),
    state VARCHAR(2) CHECK (state IS NULL OR length(state) = 2),
    zip_code VARCHAR(10)
);

CREATE TABLE customer_phone (
    customer_id INTEGER NOT NULL REFERENCES customer(customer_id) ON DELETE CASCADE,
    phone_number VARCHAR(20) NOT NULL,
    PRIMARY KEY (customer_id, phone_number)
);

CREATE TABLE device_type (
    device_type_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_name VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(255)
);

CREATE TABLE device (
    device_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER NOT NULL REFERENCES customer(customer_id) ON DELETE RESTRICT,
    device_type_id INTEGER NOT NULL REFERENCES device_type(device_type_id) ON DELETE RESTRICT,
    brand VARCHAR(50) NOT NULL,
    model VARCHAR(80) NOT NULL,
    serial_number VARCHAR(100) UNIQUE
);

CREATE TABLE technician (
    technician_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    specialty VARCHAR(100)
);

CREATE TABLE repair_job (
    repair_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id INTEGER NOT NULL REFERENCES device(device_id) ON DELETE RESTRICT,
    date_received DATE NOT NULL,
    problem_description TEXT NOT NULL,
    status VARCHAR(30) NOT NULL CHECK (
        status IN ('Received','Diagnosing','Waiting for Parts','Repairing','Completed')
    ),
    completion_date DATE,
    labor_cost DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (labor_cost >= 0),
    CHECK (completion_date IS NULL OR completion_date >= date_received)
);

CREATE TABLE part (
    part_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    part_name VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    unit_cost DOUBLE PRECISION NOT NULL CHECK (unit_cost >= 0),
    quantity_in_stock INTEGER NOT NULL DEFAULT 0 CHECK (quantity_in_stock >= 0)
);

CREATE TABLE supplier (
    supplier_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_name VARCHAR(100) NOT NULL,
    email VARCHAR(100),
    phone_number VARCHAR(20)
);

CREATE TABLE diagnostic_step (
    repair_id INTEGER NOT NULL REFERENCES repair_job(repair_id) ON DELETE CASCADE,
    step_number INTEGER NOT NULL CHECK (step_number > 0),
    technician_id INTEGER NOT NULL REFERENCES technician(technician_id) ON DELETE RESTRICT,
    description TEXT NOT NULL,
    result TEXT,
    date_performed DATE NOT NULL,
    PRIMARY KEY (repair_id, step_number)
);

CREATE TABLE repair_technician (
    repair_id INTEGER NOT NULL REFERENCES repair_job(repair_id) ON DELETE CASCADE,
    technician_id INTEGER NOT NULL REFERENCES technician(technician_id) ON DELETE RESTRICT,
    hours_worked DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (hours_worked >= 0),
    PRIMARY KEY (repair_id, technician_id)
);

CREATE TABLE repair_part (
    repair_id INTEGER NOT NULL REFERENCES repair_job(repair_id) ON DELETE CASCADE,
    part_id INTEGER NOT NULL REFERENCES part(part_id) ON DELETE RESTRICT,
    quantity_used INTEGER NOT NULL CHECK (quantity_used > 0),
    price_at_time_of_repair DOUBLE PRECISION NOT NULL CHECK (price_at_time_of_repair >= 0),
    PRIMARY KEY (repair_id, part_id)
);

CREATE TABLE supplier_part (
    supplier_id INTEGER NOT NULL REFERENCES supplier(supplier_id) ON DELETE CASCADE,
    part_id INTEGER NOT NULL REFERENCES part(part_id) ON DELETE CASCADE,
    supplier_price DOUBLE PRECISION NOT NULL CHECK (supplier_price >= 0),
    PRIMARY KEY (supplier_id, part_id)
);
